spring:
  config:
    import: optional:file:.env[.properties]
  security:
    oauth2:
      client:
        registration:
          naver:
            scope: name,email
            client-name: naver
            client-id: ${NAVER_CLIENT_ID}
            redirect-uri: ${NAVER_REDIRECT_URI}
            authorization-grant-type: authorization_code
            client-secret: ${NAVER_CLIENT_SECRET}
          google:
            authorization-grant-type: authorization_code
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            client-name: google
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile,email
          kakao:
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: ${KAKAO_REDIRECT_URI}
            authorization-grant-type: authorization_code
            client-id: ${KAKAO_CLIENT_ID}
            scope: profile_nickname
            client-name: kakao
        provider:
          kakao:
            user-name-attribute: id
            user-info-uri: https://kapi.kakao.com/v2/user/me
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
            token-uri: https://nid.naver.com/oauth2.0/token
  jpa:
    properties:
      hibernate:
        highlight_sql: 'true'
        format_sql: 'true'
        use_sql_comments: 'true'
        show_sql: 'true'
    hibernate:
      ddl-auto: update
    open-in-view: 'false'
  profiles:
    active: local
  application:
    name: dailyhub

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace
        SQL: debug
      springframework:
        transaction:
          interceptor: trace
        security:
          nodeValue: debug
          web: trace

---
# local 데이터베이스 설정
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dailyhub
    username: root
    password: 1234

authen:
  jwt:
    secret:
      key: jqporwujiefdknvznqpowerjkfljkladkjqgfhqhoeruihbnmvbjadljncxvjlxvchjf

---
# prod 데이터베이스 설정
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

authen:
  jwt:
    secret:
      key: ${JWT_SECRET_KEY}