spring:
  profiles:
    active: local

  config:
    import: optional:file:.env[.properties]

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 10MB
      max-request-size: 30MB

  jpa:
    properties:
      hibernate:
        highlight_sql: 'true'
        format_sql: 'true'
        use_sql_comments: 'true'
        show_sql: 'true'
        default_batch_fetch_size: 100
    hibernate:
      ddl-auto: update
    open-in-view: 'false'

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace
        SQL: debug
      springframework:
        transaction:
          interceptor: trace
        security:
          nodeValue: debug
          web: trace

app:
  props:
    jwt:
      secret:
        key: ${JWT_SECRET_KEY}

    aws:
      key:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      s3:
        bucket-name: ${AWS_S3_BUCKET_NAME}
        region: ${AWS_REGION}

---

# local 데이터베이스 설정

spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/dailyhub
    username: root
    password: 1234

---

# prod 데이터베이스 설정

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}



