name: Build and Push Docker Images
 
on:
  push:
    branches:
      - main
jobs:
  build_and_push: 
    runs-on: ubuntu-latest

    steps:
      # 1. DockerHub 로그인
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 2. Checkout 코드
      - name: Checkout repository
        uses: actions/checkout@v3
        
      # 3. MySQL Docker 이미지 빌드 및 푸시
      - name: Build MySQL Docker image
        working-directory: db
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/dailyhubdb .

      - name: Push MySQL Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/dailyhubdb

      # 4. Backend Docker 이미지 빌드 및 푸시
      - name: Build Backend Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/dailyhubbackend .
      - name: Push Backend Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/dailyhubbackend

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Docker pull and run
        uses: appleboy/ssh-action@master
        with:
          username: ubuntu
          host: ${{ secrets.EC2_HOST_IP }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            if [ "$(sudo docker ps -a -q -f name=dailyhubdb)" ]; then
              sudo docker rm -f dockerdb
            fi 
            if [ "$(sudo docker ps -a -q -f name=dailyhubbackend)" ]; then
              sudo docker rm -f dailyhubbackend
            fi
            if [ "$(sudo docker images -q ${{ secrets.DOCKERHUB_USERNAME }}/dailyhubdb)" ]; then
              sudo docker rmi -f ${{ secrets.DOCKERHUB_USERNAME }}/dailyhubdb
            fi
            if [ "$(sudo docker images -q ${{ secrets.DOCKERHUB_USERNAME }}/dailyhubbackend)" ]; then
              sudo docker rmi -f ${{ secrets.DOCKERHUB_USERNAME }}/dailyhubbackend
            fi
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/dailyhubdb
            sudo docker run -d -p 3308:3306 --name dailyhubdb -v db_volume:/var/lib/mysql ${{ secrets.DOCKERHUB_USERNAME }}/dailyhubdb
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/dailyhubbackend
            sudo docker run -d -p 8080:8080 --name dailyhubbackend \
            --add-host=host.docker.internal:172.17.0.1 \
            --env-file /home/ubuntu/.env \
            ${{ secrets.DOCKERHUB_USERNAME }}/dailyhubbackend
